# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt

# Install gunicorn
RUN pip3 install gunicorn

# Add gunicorn to the container's PATH
ENV PATH="/home/appuser/.local/bin:${PATH}"

# Expose port 8080 for the Flask app
EXPOSE 8080

# Start the Flask app using gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]
